### ISSUE TITLE
unexpected error in running demo

### ISSUE THREAD

**Issue by Esche-Hohenstein** [gkwnstj/GRACE#1]
hello, I meet an error when running the _python GRACE.py_ demo. The feedback info is :

root@autodl-container-beda118efa-90a789db:~/GRACE-main# python GRACE.py
gpu available :  True
############################# kolod ##############################
Traceback (most recent call last):
  File "GRACE.py", line 105, in <module>
    adj, features, n_clusters, true_label, normalized_data = my_data(dataset_str, sampling_count)
  File "/root/GRACE-main/gae/input_data_my.py", line 46, in my_data
    file = pd.read_csv('.../{}.txt'.format(data_file), sep='\t')
  File "/root/miniconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/miniconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/root/miniconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/root/miniconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/root/miniconda3/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '.../kolod.txt'
root@autodl-container-beda118efa-90a789db:~/GRACE-main# 

it seems that the file kolod.txt is required, but I could not find it anywhere. Could you give me some suggestions in solving it?

**Comment by gkwnstj** [comment]
I have uploaded multiple pieces of data, and if you need normalized data for SVM testing, it is in the 'gae' folder. Thank you for your comments!
